### PR TITLE
Hi. I've made some improvements to the app. I hope my changes will be helpful.

### PR DESCRIPTION
**Pull request by alexeydott**
+ Added support for Packed bit fields translation in c structures
+ Added ability to ignore one or more files (by mask) in directory with *.h files
+ Added ability to set user-defined type mapping
+ Added support for simple "post-processing" scripts(thanks to @tinyBigGAMES), such as creating dynamic import methods to make the final result more usable in Delphi. A detailed description of the commands can be found in the script help file (ScriptHelp.rtf)
* Fixed wrong memory access error in TParsedCommentWriter.IsBlockComment, TParsedCommentWriter.WriteChildren, related to different TCXComment structure definition for win32/win64 platforms
* Fixed a potential "type redefenition error" related to Delphi's insensitivity to the case of the character being declared.

### CODE REVIEW

**Comment by jarroddavis68** [comment]
Hmm, this looks like all of my post processing code, without any acknowledgement whatsoever????

**Comment by neslib** [comment]
@alexeydott Thanks for your contributions. These look very interesting!
Could you rename the unit "Cnet.Postprocessor" to "Chet.Postprocessor" before I review.
I will also check with Jarrod Davis if he's OK with the inclusion of his code.

**Comment by neslib** [comment]
@jarroddavis68 Looks like @alexeydott added comments with copyright attributions to your source files and changes. Does this address your concerns? I will not merge this pull request unless both of you agree with this.

**Comment by jarroddavis68** [comment]
@neslib Yes, I have spoken to him already, all good now. Thank you both.

**Comment by neslib** [comment]
> @neslib Yes, I have spoken to him already, all good now. Thank you both.

Thank you!

**Comment by alexeydott** [comment]
done)

**Pull request merged**
